### ISSUE TITLE
IDM 2023 Organisation

### ISSUE THREAD

**Issue by andrevidela** [idris-lang/Idris2#3012]
## Meta

This is an issue to keep track of the management of the Idris developer meeting, this is _not_ the announcement. This issue exists to give visibility to the community as to how the event is organised. This with the aim to be easier to reach for suggestions, kept accountable and train other people to organise such events.

## To do Pre

- [x] write Discord announcement
- [x] write Wiki announcement
- [x] write mailing list announcement
- [x] Proofread the post in its various forms
- [x] Double check timezone
- [x] post to mailing list 
- [x] post on the wiki 
- [x] post on SPLS Zulip
- [x] post on Discord
- [x] announce on twitter (who's got access except edwin?)
	- [x] Mastodon?
- [x] update wiki sidebar and main page 
- [x] setup discord role
- [x] find a speaker for the first day
- [x] Create a list of topics and projects for the week
- [x] make sure the links are available on discord
  - [x] link to the wiki
  - [x] link to gather.town
- [x] Check if we have a good selection of "good first issue"
- [x] Do we have a good way to teach people how to schedule the events?

## Todo on the day

- [x] Unarchive the developer meeting channel
- [x] Make an extra announcement using the new role

## Todo Post

- [x] Archive the developer meeting channel
- [x] prepare for release, if any.
- [x] Close this issue
- [x] remove the registration message
- [x] Resore wiki sidebar and main page

## Info

Date: 28.08-01.09
location: St-Andrews (UTC+1), Zurich (UTC+2), Discord
Programme:
- Monday - 10am UTC+1 : kick off
- Friday - 3pm UTC+1: Show & tell + conclusion

### Discord Announcement

Hello everyone,

We're announcing the next Idris Developer Meeting, it will start Monday 28th of August and will end September 1st. This year,  in addition to Discord, we are holding the meeting in two physical locations: Like before, you can join us in St-Andrews, but we will also have a location in Zurich. The Idris developer meeting is a small event so we're only providing one room and nothing else.

If you've never participated to a Developer Meeting before, it's an event where the community joins forces to meet and work together for a week on the Idris compiler, and other related projects. We prepare project ideas that people might be interested in building, issues that people might pick up and talks to showcase what the community has been working on. you are encouraged to give a talk about your work during the week.  They usually range from 10m to 1h. 

You do not need to be an Idris expert or a compiler engineer to participate, all contributions are welcome and this time is the best to learn the language with the help of the available community members. Before parting on the last day we share each other's work in a small show&tell session. All the events are held on discord in order to accommodate as many people as we can. If you want to meet in person you can join us at one of the two locations above.

To register for the event and get all notifications, please go to the #roles channel and click the reaction emoji. 

### Wiki message

---

## Date

Monday the 28th of August - Friday the 1st of September 2023

## Aim

Spend some time hacking together and have a good time!

## Location

The event will take place in three locations:
- The [idris2 discord][DISCORD] where you will find talks, online discussions and channels to coordinate your projects
- St-Andrews University (UTC+1), where you will be able to meet in person 
- Zurich (UTC+2) , where you will be able to meet in person as well

All the information about the event is coordinated on discord. You can register by selecting the appropriate role in the `#🪄│roles` channel.

Be aware of the timezone, all events will be communicated in UTC+1 to reflect the Scottish timezone.

## Format

During the week, there will be talks, discussions, coding sessions and time for socialising. The programme is community driven, and will evolve during the week. All updates will be posted here. If you have a suggestion for a talk you want to give, or have a discussion topic to propose, please add those below. Usually, most talks happen on Wednesday but there is no strong rule if you cannot make it on Wednesday.

### Programme

- Monday 28/08/2022 10:00 UTC+1: Introduction
- Friday 01/09/2022 15:00 UTC+1: [Show & Tell](#show-and-tell-friday-1500-utc-1) + Conclusion

### Project ideas

Some things you might choose to work on during the week (please add any you can think of):

- A runtime debugger
- A cool REPL
- Help on the new core? (TBD by edwin)

## Show and Tell (Friday 15:00 UTC +1)

Tell us what you did during the week!  Add your name here if you have something you want to show or contact one of the other moderators on discord, any time before the start.

## Participants/Registration

If you plan to attend and wish to advertise it, please record your name in the list below. You might want to add the location from which you plan to attend (St-Andrews, Zurich or Discord).

Please also consider adding your timezone, so that we can avoid scheduling too many things when people are asleep. 
In discord you can add it to your description. Participants are reminded that we expect the [Idris Community Standards](https://www.idris-lang.org/pages/community-standards.html) to be upheld throughout.

[DISCORD]: https://discord.gg/UX68fDs2jc
[GT]: gather.town

---

### Mailing list announcement

Dear Idris community,

We are announcing the date for the next Idris Developer Meeting: August 28th 2023. The even will run until Friday 1st of September.

This year, the developer meeting will take place online on discord and in-person. We have two locations if you wish to meet in-person: St-Andrews and Zurich. Because the talks and the project coordination will take place on discord, you are encouraged to join the server and register your participation in the #🪄│roles channel. 

What is the Idris Developer Meeting?

It's an event to bring the Idris community together to hack, learn and socialise. You are encouraged to show your work, project ideas and experiments with the language. For this we've setup a calendar bot in discord with which you can schedule a presentation. Usually those range from 10m to 1h. At the end of the week, we have a Show & Tell session where we share the worked that's been done and make a short demo. The following days are dedicated to cleaning up Pull requests and releasing the features everyone has been working on.

Who can participate?

Everyone is welcome to participate. You do not need to be an Idris expert or a compiler engineer to participate, all contributions are welcome and this time is the best to learn the language with the help of the available community members. 

---
### Zulip Announcement

Hi everyone, we're organising the next Idris Developer Meeting and it will be between the 28th of August and the 1st of September. Like before, the talks and coordination will be on Discord, but we will also have two physical locations if you wish to meet in-person: St-Andrews and Zurich.

A summary of the information is on the wiki https://github.com/idris-lang/Idris2/wiki/Idris-Developer-Meeting,-August-2023 you will have to join the discord (https://discord.gg/UX68fDs2jc) in order to get notifications and participate in the talks and group chats.

If you have an idea for a project, please add it to the page on the wiki.

**Comment by andrevidela** [comment]
I wonder if there is any way to allow participants on discord to submit project idea and have other people vote/join the project
